//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int id_avion { get; set; }
        public Nullable<int> numfila_avion { get; set; }
        public Nullable<int> numcolumna_avion { get; set; }
        public string nombre_avion { get; set; }
        public Nullable<int> id_aerolinea { get; set; }
        public Nullable<int> id_secciones { get; set; }
        public string modelo_avion { get; set; }
        public Nullable<int> num_asientos { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
        public virtual Secciones Secciones { get; set; }
    }
}
