//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.Vuelos = new HashSet<Vuelos>();
        }
    
        public int id_avion { get; set; }
        public Nullable<int> numfila_avion { get; set; }
        public Nullable<int> numcolumna_avion { get; set; }
        public string nombre_avion { get; set; }
        public Nullable<int> id_aerolinea { get; set; }
        public Nullable<int> id_secciones { get; set; }
        public string modelo_avion { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelos> Vuelos { get; set; }
        public virtual Secciones Secciones { get; set; }
    }
}
