//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleto()
        {
            this.Compra = new HashSet<Compra>();
        }
    
        public int id_boleto { get; set; }
        public Nullable<int> id_vuelo { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_pasajero { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual Pasajeros Pasajeros { get; set; }
        public virtual Vuelos Vuelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}
