//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public int id_compra { get; set; }
        public Nullable<System.DateTime> Fecha_compra { get; set; }
        public Nullable<System.DateTime> Hora_compra { get; set; }
        public Nullable<decimal> Precio_compra { get; set; }
        public Nullable<int> id_tarjeta { get; set; }
        public Nullable<int> id_estadopago { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> id_metodopago { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Estado_pago Estado_pago { get; set; }
        public virtual Metodo_pago Metodo_pago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
    }
}
